'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'frontend', 'dist');
const indexPath = path.join(dist, 'index.html');
const outputPath = path.join(root, 'generated', 'app-html.js');

if (!fs.existsSync(indexPath)) {
  console.error('frontend/dist/index.html does not exist. Run npm run build:ui first.');
  process.exit(1);
}

let html = fs.readFileSync(indexPath, 'utf8');

function readAsset(url) {
  const clean = url.replace(/^\.\//, '').replace(/^\//, '');
  const file = path.join(dist, clean);
  if (!fs.existsSync(file)) throw new Error(`Built asset not found: ${url}`);
  return fs.readFileSync(file, 'utf8');
}

// Inline CSS so the production binary never reads frontend files at runtime.
html = html.replace(/<link\s+rel=["']stylesheet["'](?:\s+crossorigin)?\s+href=["']([^"']+)["']\s*\/?>/g, (_m, href) => {
  const css = readAsset(href).replace(/<\/style/gi, '<\\/style');
  return `<style>${css}</style>`;
});

// IMPORTANT: keep the inlined Vite bundle as type="module".
// Vite normally emits a module script in <head>. Module scripts are deferred
// until the document has been parsed, so #root exists when React calls
// createRoot(). The old embedder converted it to a classic inline <script>,
// which executed immediately in <head> and caused React minified error #299.
html = html.replace(/<script\s+type=["']module["'](?:\s+crossorigin)?\s+src=["']([^"']+)["']><\/script>/g, (_m, src) => {
  const js = readAsset(src).replace(/<\/script/gi, '<\\/script');
  return `<script type="module">${js}</script>`;
});

if (/\b(?:src|href)=["']\.?\/assets\//.test(html)) {
  throw new Error('Not all Vite assets were inlined. Refusing to create a runtime-dependent bundle.');
}

if (!/<div\s+id=["']root["']/.test(html)) {
  throw new Error('Built HTML is missing the React #root mount element.');
}

const moduleSource = `'use strict';\n\n// Generated by scripts/embed-ui.js. Do not edit manually.\nmodule.exports = ${JSON.stringify(html)};\n`;
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, moduleSource, 'utf8');

const kb = Math.round(Buffer.byteLength(html) / 1024);
console.log(`Embedded React/Vite/Tailwind UI: ${kb} KiB -> ${path.relative(root, outputPath)}`);
